# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '15.0' # or platform :osx, '10.10' if your target is OS X.
use_frameworks!

target 'NhaDoiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Swinject'

  pod 'SwinjectStoryboard'

  # Pods for NhaDoiOS

  target 'NhaDoiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NhaDoiOSUITests' do
    # Pods for testing
  end

end

